name: Crawler

on:
  schedule:
    - cron: "0 0 */3 * *"

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        cd crawler
        pip install -r requirements.txt

    - name: Run crawler
      run: |
        cd crawler
        python main.py
