name: Crawler

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */3 * *"

jobs:
  crawl:
    runs-on: windows-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.2.0
      - name: Download Chrome Driver
        run: |
          Invoke-WebRequest "https://chromedriver.storage.googleapis.com/LATEST_RELEASE" -OutFile "latest.txt"
          $latest = Get-Content -Path "latest.txt"
          Invoke-WebRequest "https://chromedriver.storage.googleapis.com/$($latest)/chromedriver_win32.zip" -OutFile "chromedriver.zip"
          Expand-Archive -Path "chromedriver.zip" -DestinationPath "."

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install all necessary packages
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2 urllib3 python-dotenv selenium scrapy
      - name: Run crawler
        run: python crawler/main.py
