name: Crawler

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */3 * *"

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v2.0.0
      - name: Install all necessary packages
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2 urllib3 python-dotenv selenium scrapy
      - name: Run crawler
        run: python crawler/main.py
        
      
