name: Crawler

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */3 * *"

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Download Firefox
        run: |
          sudo apt-get update && sudo apt-get install -y firefox
      - name: Download Geckodriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
          tar xzvf geckodriver-v0.30.0-linux64.tar.gz
      - name: Set up Firefox
        uses: nanasess/setup-geckodriver@v2.0.0
        with:
          geckodriver-version: "v0.30.0"
          geckodriver-path: ./geckodriver

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install all necessary packages
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2 urllib3 python-dotenv selenium scrapy
      - name: Run crawler
        run: python crawler/main.py
